#!/bin/bash
#
# install script

[ -d "~/.config/nvim" ] && cp init.vim ~/.config/nvim/init.vim || mkdir ~/.config/nvim && cp init.vim ~/.config/nvim/init.vim
cp config.neomuttrc ~/.neomuttrc
mkdir ~/.mutt
echo 'Make sure to setup neomutt with your email account!'

echo 'Installing vim-plug. [ret] to continue.'
read
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

nvim -c 'PlugInstall' \
	 -c 'qa!'
	 
echo 'Installing gum. [ret] to continue.'
read
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
sudo apt update && sudo apt install gum
	 
echo 'Installed dotfiles!'
